/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "f17d8dc5121c0fb112796be1d3194ed2f1c0e2b8"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
