/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "da3787ba355f18db7db52abf75c42afb408d656f"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
